### ISSUE TITLE
Error: invalid or missing API key

### ISSUE THREAD

**Issue by HarasimowiczKamil** [igorprado/nodebb-plugin-sso-steam#14]
I install plugin, restart nodebb. Set API key and again restart nodebb. key is in redis:

```
127.0.0.1:6379> hget config social:steam:apikey
"*****************************************************"
```

(instead of stars is my key, of course).
And then i can't start nodebb, in log i have:

```
error: invalid or missing API key
Error: invalid or missing API key
    at new steam (/home/www-pages/nodebb/node_modules/nodebb-plugin-sso-steam/node_modules/passport-steam/node_modules/steam-web/lib/steam.js:20:80)
    at new Strategy (/home/www-pages/nodebb/node_modules/nodebb-plugin-sso-steam/node_modules/passport-steam/lib/passport-steam/strategy.js:49:17)
    at Object.Steam.getStrategy (/home/www-pages/nodebb/node_modules/nodebb-plugin-sso-steam/library.js:37:20)
    at /home/www-pages/nodebb/src/plugins.js:377:32
    at /home/www-pages/nodebb/node_modules/async/lib/async.js:272:13
    at iterate (/home/www-pages/nodebb/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/home/www-pages/nodebb/node_modules/async/lib/async.js:165:9)
    at Object.async.reduce (/home/www-pages/nodebb/node_modules/async/lib/async.js:271:15)
    at Object.Plugins.fireHook (/home/www-pages/nodebb/src/plugins.js:371:12)
    at /home/www-pages/nodebb/src/routes/authentication.js:140:12
```

I can remove key from redis and then run nodebb but plugin still not working :(

**Comment by igorprado** [comment]
Please try the latest version with NodeBB 0.6.x
